stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs: 
    - data/raw

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs: 
    - data/interim

  feature_engg:
    cmd: python src/feature_engg.py
    deps:
    - data/interim
    - src/feature_engg.py
    params:
    - feature_engg.max_features
    outs: 
    - data/processed

  model_building:
    cmd: python src/Model_training.py
    deps:
    - data/processed
    - src/Model_training.py
    params:
    - model_building.n_estimators
    - model_building.random_state
    outs: 
    - models/model.pkl

  model_evaluation:
    cmd: python src/Model_evaluation.py
    deps:
      - models/model.pkl
      - src/Model_evaluation.py
    metrics:
      - reports/metrics.json
